### PR TITLE
Hi Alexander. I've changed ObjectIn.factory and Field.from methods to use Option[DBObject]. All implementers of the factory method were updated accordingly. All tests successfully passed.

### PR DESCRIPTION
**Pull request by dobrynya**

### CODE REVIEW

**Comment by alaz** [comment]
Sorry for the delay. Please give me some time to think about it.

**Comment by dobrynya** [comment]
Of course.

**Comment by alaz** [comment]
Please see https://github.com/osinka/mongo-scala-driver/compare/09-factoryPf -- I am showing this technique of defining factories as a trait here, but I have a plan to make it the default in version 0.9. I guess it should simplify your Router as well.

BTW, I am going to get rid of "constraints" and "*" as a consequence -- I see no reason in them anymore. Again, hopefully these changes will simplify working around polymorphic collections/shapes as well.

**Comment by alaz** [comment]
Dmitry, please see wip-0.9 branch -- there is a good deal of preparations to working on polymorphic collections in there. Your "Router" implementation could be simplified to a kind of

```
class PolyShape[T](val shapes: List[ObjectShape[T]]) extends ObjectShape[T] {
 def factory: FactoryPF = shapes map {_.factory} reduceLeft {_ orElse _}
 def objectFields(x: T) = shapes find { /* x is an object of shape */ } map {_.objectFields(x)} toList
}
```

It's not possible unfortunately because ObjectShape is invariant...

I guess I addressed all the ideas in your pull request or missed smth?

**Comment by dobrynya** [comment]
Yes, the idea is to provide the ability to store/retrieve rich hierarchy in/from the same collection.
There may be a performance issue with this implementation because isDefinedAt will be called on all the partial functions in the worst case. Maybe efforts will not be essential. In my implementation I differentiate shapes using an entity class as the criterion. 
btw, is it worth to separate MongoField and FieldContent?
In this case it will be simple to create one's own serializers/deserializers.
class ScalarField[A : FieldContent](...). 
F.e. if user wants to store BigDecimal he provides implicit FieldContent[BigDecimal]. There is no need to extend ShapeFields.

**Comment by alaz** [comment]
Agree, there will be some performance hit. However, having a "class id" as a field does not guarantee you are able to extract it. So every approach has its pros and cons.

Personally, I prefer to have more flexibility in extracting an object from DBObject. BTW, in your Router implementation you may implement factory's `isDefinedAt` via `fqtn` -- this gonna be more effective.

Re: implicit FieldContent -- yes, I have an idea to implement fields in this way.

**Comment by dobrynya** [comment]
Some questions with PolyShape still remain.
1. Imagine that we have the following:
   class One(val f: String) extends MongoObject
   class Two(f: String, val f1: Option[String]) extends One(f)

OneShape.factory: FactoryPF  = { case f(f) => new One(f) }
TwoShape.factory: FactoryPF = { case f(f) ~ optionalf1(f1) => new Two(f, f1) }
Which factory will process a DBObject? Suspect the first one. This issue is a restriction on the model design.
1. How to choose a particular shape during serializing an object into DBObject? We need shapes to be associated to types they can process.

I hope I could explain my thoughts clearly.

**Comment by alaz** [comment]
1. Yes, the order of shapes in the constructor is important.
2. only if shapes will contain `classOf[T]`

I still have no plans to provide polymorphic shapes out of the box in the library -- namely because of all these questions arising. People may override `factory` and `objectFields` and have very granular control of the behavior.

**Pull request closed without merging**
